### PR TITLE
Multiple games

### PR DESCRIPTION
**Pull request by dgutt17**

### CODE REVIEW

**Review by danparnella — COMMENTED** [review]
Seems to be working! I did get an error in the logs (https://share.getcloudapp.com/Jru1Wqq8), but might not be something we need to worry about right now.

Mind if push the updated yarn.lock file? That way the new `dotenv` dependency will be installed on yarn start.

**Comment by dgutt17** [comment]
The reason that came up was because you don't have a postgres user in your postgres db. 

I should of listed out how to get it to work first, but here are the instructions:
1. Run `npm install`
2. In postgres version 10 create a space_dev db with `createdb space_dev`
3. Run the migrations with `npx sequelize-cli db:migrate`

So creating multiple games has not been completely implemented. This PR creates the setup for it. Specifically:
1. The Database Modeling, ORM, and connection to Postgres have been built
2. Random Room Tags are generated for player 1
3. Player 1 creates a game instance in postgres and a player instance associated with the game instance
4. Player 1 is added to a socket.io room
5. Player 2 uses query params to add its self to the same socket.io room as player 1
6. Player 2 also creates a player instance and associates it to the correct game instance

**Comment by dgutt17** [comment]
@danparnella You can push up the new yarn lock

**Comment by danparnella** [comment]
> The reason that came up was because you don't have a postgres user in your postgres db.
> 
> I should of listed out how to get it to work first, but here are the instructions:
> 
> 1. Run `npm install`
> 2. In postgres version 10 create a space_dev db with `createdb space_dev`
> 3. Run the migrations with `npx sequelize-cli db:migrate`

I'm sure I missed a step (super noob on backend and DBs so bear with me), but I got `role "postgres" does not exist` error after running the last command.

**Comment by dgutt17** [comment]
> > The reason that came up was because you don't have a postgres user in your postgres db.
> > I should of listed out how to get it to work first, but here are the instructions:
> > 
> > 1. Run `npm install`
> > 2. In postgres version 10 create a space_dev db with `createdb space_dev`
> > 3. Run the migrations with `npx sequelize-cli db:migrate`
> 
> I'm sure I missed a step (super noob on backend and DBs so bear with me), but I got `role "postgres" does not exist` error after running the last command.

You are missing a postgres user called `postgres`. If you check the config.json folder for sequelize it is expecting a user called `postgres`. I can show you when have our meeting today. 

If you want to check yourself you have to enter your `psql` shell. If you type `psql` on your terminal you should enter the `psql` shell. After that type `\du`. This shoild list out all your users or `roles`. If you don't see a `postgres` role you will need to add one.

**Pull request merged**
